set nocompatible

"
" initialisation de pathogen
"
call pathogen#infect()
call pathogen#helptags()



" load all config files
runtime! config/**/*.vim

"
" mac os specific settings
" :cd /Users/stephanegesuati/workspace/repos
" set visualbell t_vb=
